language: node_js
node_js:
    - '6'
before_script:
    - npm install && npm install -g codecov
script:
    - npm run test
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    - codecov
after_success:
    - bash <(curl -s https://codecov.io/bash)
